---
abstract: 'Dynamically add stopwords to your woven pod'
author:
  - 'Randy Stauner <rwstauner@cpan.org>'
build_requires:
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Moose::Autobox: 0.10
  PPI: 0
  Pod::Elemental: 0.102360
  Pod::Elemental::Selectors: 0
  Pod::Elemental::Transformer::Nester: 0
  Pod::Elemental::Transformer::Pod5: 0
  Software::License::Perl_5: 0
  Test::Differences: 0.500
  Test::MockObject: 1.09
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-Plugin-StopWords
no_index:
  directory:
    - corpus
    - examples
    - inc
    - share
    - t
    - xt
  namespace:
    - Local
    - t::lib
  package:
    - DB
provides:
  Pod::Weaver::Plugin::StopWords:
    file: lib/Pod/Weaver/Plugin/StopWords.pm
    version: 1.003
requires:
  Moose: 0
  Moose::Autobox: 0
  Pod::Weaver: 3.101632
  Pod::Weaver::Role::Finalizer: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Weaver-Plugin-StopWords
  homepage: http://github.com/magnificent-tears/Pod-Weaver-Plugin-StopWords/tree
  repository: git://github.com/magnificent-tears/Pod-Weaver-Plugin-StopWords.git
version: 1.003
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::RWSTAUNER/Git::NextVersion'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::GenerateFile
      name: '@Author::RWSTAUNER/GenerateManifestSkip'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::RWSTAUNER/GatherDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::RWSTAUNER/PruneCruft'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::RWSTAUNER/ManifestSkip'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::RWSTAUNER/PruneBuilderFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::RWSTAUNER/PruneRepoMetaFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::RWSTAUNER/Authority'
      version: 1.004
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::RWSTAUNER/NextRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::RWSTAUNER/PkgVersion'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Author::RWSTAUNER/Prepender'
      version: 1.103470
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::RWSTAUNER/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::RWSTAUNER/License'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::RWSTAUNER/Readme'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Author::RWSTAUNER/Bugtracker'
      version: 1.102670
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Author::RWSTAUNER/Repository'
      version: 0.17
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::RWSTAUNER/GithubMeta'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::RWSTAUNER/AutoPrereqs'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::RWSTAUNER/MetaNoIndex'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Author::RWSTAUNER/MetaProvides::Package'
      version: 1.12060501
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::RWSTAUNER/MinimumPerl'
      version: 1.002
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::RWSTAUNER/MetaConfig'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::RWSTAUNER/MetaYAML'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::RWSTAUNER/MetaJSON'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Author::RWSTAUNER/TestMoreWithSubtests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::RWSTAUNER/ExtraTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::RWSTAUNER/ExecDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::RWSTAUNER/ShareDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::RWSTAUNER/MakeMaker'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::RWSTAUNER/ModuleBuild'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::DualBuilders
      name: '@Author::RWSTAUNER/DualBuilders'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::RWSTAUNER/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::PodSpellingTests
      name: '@Author::RWSTAUNER/PodSpellingTests'
      version: 1.103491
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@Author::RWSTAUNER/Test::Pod::LinkCheck'
      version: 0.001
    -
      class: Dist::Zilla::Plugin::Test::Pod::No404s
      name: '@Author::RWSTAUNER/Test::Pod::No404s'
      version: 0.001
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@Author::RWSTAUNER/@TestingMania/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@Author::RWSTAUNER/@TestingMania/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::RWSTAUNER/@TestingMania/PodCoverageTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@Author::RWSTAUNER/@TestingMania/CompileTests'
      version: 1.110930
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::RWSTAUNER/@TestingMania/Test::CPAN::Changes'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::RWSTAUNER/@TestingMania/MetaTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@Author::RWSTAUNER/@TestingMania/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@Author::RWSTAUNER/@TestingMania/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@Author::RWSTAUNER/@TestingMania/CriticTests'
      version: 1.102280
    -
      class: Dist::Zilla::Plugin::DistManifestTests
      name: '@Author::RWSTAUNER/@TestingMania/DistManifestTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Author::RWSTAUNER/@TestingMania/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::RWSTAUNER/@TestingMania/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Author::RWSTAUNER/@TestingMania/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::RWSTAUNER/@TestingMania/PodSyntaxTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::RWSTAUNER/Manifest'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@Author::RWSTAUNER/CheckChangesHasContent'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::RWSTAUNER/TestRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::RWSTAUNER/ConfirmRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::RWSTAUNER/UploadToCPAN'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::RWSTAUNER/@Git/Check'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::RWSTAUNER/@Git/Commit'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::RWSTAUNER/@Git/Tag'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::RWSTAUNER/@Git/Push'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::RWSTAUNER/InstallRelease'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: suggests
      name: RuntimeSuggests
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200004
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200004
x_authority: cpan:RWSTAUNER
